---

### Agent 
- name: Agents setup - Info
  uri: 
    url: http://192.168.0.3:5601/api/fleet/agents/setup
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_agent_setup
  tags:
    - get_agent_setup

- name: Agents - List
  uri: 
    url: http://192.168.0.3:5601/api/fleet/agents
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_agent_list
  no_log: true
  tags:
    - get_agent_list

- name: Agents - Info
  uri: 
    url: http://192.168.0.3:5601/api/fleet/agents/b8264bd5-34fa-4311-99f0-34e082ef143a
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_agent_info
  no_log: true
  tags:
    - get_agent_info

- name: Agent - Unenroll
  uri: 
    url: "{{fleet_base_url}}/agents/{{agentId}}/unenroll"
    method: POST
    body: '{ "revoke": true, "force": true }'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: unenroll_agent
  tags:
    - unenroll_agent

### Enrollment
- name: Get Enrollment api-keys
  uri: 
    url: http://192.168.0.3:5601/api/fleet/enrollment-api-keys
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_enrollment_keys
  tags:
    - get_enrollment_keys

- name: Get Enrollment api-keys
  uri: 
    url: http://192.168.0.3:5601/api/fleet/enrollment-api-keys/{{keyId}}
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_enrollment_keys_info
  tags:
    - get_enrollment_keys_info

### Policies 
- name: Get Agent Policies List
  uri: 
    url: http://192.168.0.3:5601/api/fleet/agent_policies
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_agent_policy_list
  tags:
    - get_agent_policy_list

- name: Get Agent Policies Info
  uri: 
    url: http://192.168.0.3:5601/api/fleet/agent_policies/{{agentPolicyId}}
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_agent_policy_info
  tags:
    - get_agent_policy_info

- name: Copy Agent Policy
  uri: 
    url: "{{fleet_base_url}}/agent_policies/{{agentPolicyId}}/copy"
    method: POST
    body:  '{ "name": "Test Test","description": "Generated by Fleet API Copy of {{agentPolicyId}}"}'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: copy_agent_policy
  tags:
    - copy_agent_policy

- name: Update Agent Policy
  uri: 
    url: http://192.168.0.3:5601/api/fleet/agent_policies/{{agentPolicyId}}
    method: PUT
    body: '{"name": "Test Policy","namespace": "testnamespace","description": "Generated by Fleet API - Ansible","monitoring_enabled": ["logs","metrics"]}'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: update_agent_policy
  tags:
    - update_agent_policy

- name: Delete Agent Policy
  uri: 
    url: "{{fleet_base_url}}/agent_policies/delete"
    method: POST
    body: '{ "agentPolicyId": "{{agentPolicyId}}" }'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: delete_agent_policy
  tags:
    - delete_agent_policy

### Package Policies 

- name: Package policies - List
  uri: 
    url: "{{fleet_base_url}}/package_policies"
    method: GET
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
  register: get_package_policies_list
  tags:
    - get_package_policies_list

- name: Package policy - Info
  uri: 
    url: "{{fleet_base_url}}/package_policies/{{packagePolicyId}}"
    method: GET
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
  register: get_package_policies_info
  tags:
    - get_package_policies_info

- name: Package policy - Delete
  uri: 
    url: "{{fleet_base_url}}/package_policies/delete"
    method: POST
    body: '{"packagePolicyIds": ["{{packagePolicyId}}"],"force": true}'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: delete_package_policies
  tags:
    - delete_package_policies

- name: Package policy - Update
  uri:
    follow_redirects: safe
    validate_certs: false
    timeout: 5 
    url: "{{fleet_base_url}}/package_policies/{{packagePolicyId}}"
    method: PUT
    body: 
      '{
        
      }'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: update_package_policies
  tags:
    - update_package_policies

# Package policy - Delete

- name: Get Fleet Outputs 
  uri: 
    url: http://192.168.0.3:5601/api/fleet/outputs
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_fleet_outputs
  tags:
    - get_fleet_outputs

### Outputs
- name: Get Fleet Outputs Info
  uri: 
    url: http://192.168.0.3:5601/api/fleet/outputs/{{outputId}}
    method: GET
    user: "elastic"
    password: "elkpassword"
    force_basic_auth: yes
  register: get_fleet_outputs_info
  tags:
    - get_fleet_outputs_info

- name: Update Fleet Elasticsearch Output 
  uri: 
    url: http://192.168.0.3:5601/api/fleet/outputs/{{outputId}}
    method: PUT
    body: '{"hosts": "https://elasticsearch.siobytes.com:443", "ca_sha256": "string", "config": {}, "config_yaml": ""}'
    user: "{{httpUsername}}"
    password: "{{httpPassword}}"
    force_basic_auth: yes
    body_format: json
    status_code: 200,404
    headers:
      Content-Type: application/json
      kbn-xsrf: string
  register: update_agent_outputs
  tags:
    - update_agent_outputs

###
# "name": "string","namespace": "string","description": "string","monitoring_enabled": ["metrics"]
# f0d441a7-5c8e-4235-a9fb-59f00e412814